/**
 * Created by sashaz on 12.09.16.
 */

var GAME_CANVAS_WIDTH = 640,
    GAME_CANVAS_HEIGHT = 480,
    PLAYER_WIDTH = 32,
    PLAYER_HEIGHT = 33,
    PLAYER_GRAVITY = 600,
    PLAYER_VELOCITY = 180,
    PLAYER_JUMP_VELOCITY = -300,
    BLOCK_SIZE = 40,

    BOX_BOTTOM = GAME_CANVAS_HEIGHT - BLOCK_SIZE;